### ISSUE TITLE
Get rid of System.out.println & printStackTrace calls

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle-lib#15]
These are annoying, and can't be controlled in the same way that logging can. Plus, thewca/tnoodle#112 kind of requires this.

This issue can be closed once we've gone through all our code and removed the offending calls, and then added a precommit hook to make sure we don't add any new ones.

**Comment by suushiemaniac** [comment]
The SysOut calls have been cleaned up and implemented as proper logger calls in https://github.com/thewca/tnoodle-lib/pull/11
